### ISSUE TITLE
Error parsing server error response: VenafiServerError does not match actual structure

### ISSUE THREAD

**Issue by FooBarWidget** [Venafi/vcert-java#13]
When I request a certificate with invalid parameters, Venafi Cloud responds with an error. VCert-java fails to parse this error response, because the VenafiServerError class does not match the actual response structure.

Here is the response I got from the server:

~~~json
{
   "errors":[
      {
         "code":10726,
         "message":"Distinguished name component O with value \"\" is invalid",
         "args":[
            "O",
            "",
            [
               "Fullstaq"
            ]
         ]
      },
      {
         "code":10726,
         "message":"Distinguished name component OU with value \"\" is invalid",
         "args":[
            "OU",
            "",
            [
               "DevOps"
            ]
         ]
      },
      {
         "code":10726,
         "message":"Distinguished name component L with value \"\" is invalid",
         "args":[
            "L",
            "",
            [
               "Oosterhout"
            ]
         ]
      },
      {
         "code":10726,
         "message":"Distinguished name component ST with value \"\" is invalid",
         "args":[
            "ST",
            "",
            [
               "NB"
            ]
         ]
      },
      {
         "code":10726,
         "message":"Distinguished name component C with value \"\" is invalid",
         "args":[
            "C",
            "",
            [
               "NL"
            ]
         ]
      }
   ]
}
~~~

VenafiServerError is defined as follows:

~~~java
private static class VenafiServerError {
    private int code;
    private String message;
    private Collection<String> args;   // <----- !!!!
}
~~~

However, as you can see in the actual response, errors[x].args[2] is an array.

As a result, vcert-java throws an IllegalStateException:

~~~
java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 112 path $.errors[0].args[2]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:838)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:422)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:410)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
Caused: com.google.gson.JsonSyntaxException
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
	at com.google.gson.Gson.fromJson(Gson.java:861)
	at com.google.gson.Gson.fromJson(Gson.java:826)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:747)
	at com.venafi.vcert.sdk.VCertException.fromFeignException(VCertException.java:49)
	at com.venafi.vcert.sdk.VCertClient.requestCertificate(VCertClient.java:170)
~~~

**Comment by tr1ck3r** [comment]
@FooBarWidget can you confirm you are using the current release ([v0.1.3](https://github.com/Venafi/vcert-java/releases/tag/v0.1.3)) or building from master?  We believe this issue was fixed in PR https://github.com/Venafi/vcert-java/pull/10.  The `VenafiServerError` definition was [changed](https://github.com/Venafi/vcert-java/blob/master/src/main/java/com/venafi/vcert/sdk/VCertException.java#L75).

**Comment by tr1ck3r** [comment]
@FooBarWidget can you please confirm you are using the current release jar or building from master?

**Comment by FooBarWidget** [comment]
I am building from master. I am using the 0.1.3 tag.

**Comment by tr1ck3r** [comment]
Thank you for confirming @FooBarWidget.  It appears we had a problem with our release automation and the last 2 commits weren't included.  I've re-released [v0.1.3](https://github.com/Venafi/vcert-java/releases/tag/v0.1.3).  Apologies for the confusion, please let us know if that hasn't addressed this issue.

**Comment by tr1ck3r** [comment]
@FooBarWidget did the re-released [v0.1.3](https://github.com/Venafi/vcert-java/releases/tag/v0.1.3) jar resolve this issue for you?

**Comment by FooBarWidget** [comment]
@tr1ck3r I am not able to verify whether the re-release solved for me. The reason is because I'm using vcert-java through jitpack.io, because vcert-java is not published to Maven Central (see also #14). It appears that jitpack.io performs some sort of caching. As a result, I'm not able to download your re-release via jitpack.io: it gives me the previous release.

I suggest releasing v0.1.4.

**Comment by tr1ck3r** [comment]
@FooBarWidget thank you for reporting that.  I agree it appears JitPack didn't recognize the re-release of v0.1.3.  We had a couple of pending Dependabot alerts so I addressed those and just released [v0.1.4](https://github.com/Venafi/vcert-java/releases/tag/v0.1.4) and I see it listed on https://jitpack.io/#venafi/vcert-java so hopefully that finally addresses this issue for you.  Please let me know.

**Comment by FooBarWidget** [comment]
Thanks. I confirm that 0.1.4 fixes this issue.

**Comment by tr1ck3r** [comment]
Great, thank you for confirming @FooBarWidget
