### ISSUE TITLE
Nullpointer Exception trying to renew a certificate

### ISSUE THREAD

**Issue by marcos-albornoz** [Venafi/vcert-java#53]
**PROBLEM SUMMARY**
When it's to attemped to renew a certificate on TPP passing a `RenewalRequest `which is containing a `CertificateRequest `configured with `CsrOriginOption.ServiceGeneratedCS`R then a nullpointer exception is thrown.

**STEPS TO REPRODUCE**
1. Create a `com.venafi.vcert.sdk.certificate.CertificateRequest.CertificateRequest` object and populate it as it's required ensuring to have the `csrOrigin` property set to` CsrOriginOption.ServiceGeneratedCSR`.
2. Create a `com.venafi.vcert.sdk.certificate.RenewalRequest.RenewalRequest` setting it the CertificateRequest object created previously.
3. Call the `VCertClient.renewCertificate()` method passing the RenewalRequest object created previously.

**EXPECTED RESULTS**
The call to `VCertClient.renewCertificate()` method should works successfully.

**ACTUAL RESULTS**
The call to `VCertClient.renewCertificate()`  is failing with the following:
```
Caused by: java.lang.NullPointerException: null
	at com.venafi.vcert.sdk.connectors.tpp.TppConnector.renewCertificate(TppConnector.java:408)
	at com.venafi.vcert.sdk.VCertClient.renewCertificate(VCertClient.java:202)
	... 2 common frames omitted
```

**Comment by marcos-albornoz** [comment]
The issue is already fixed in release [v0.7.1](https://github.com/Venafi/vcert-java/releases/tag/0.7.1)
